---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: __APP_ENV_NAME__
  namespace: hello
  labels:
    app: __APP_ENV_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __APP_ENV_NAME__
  template:
    metadata:
      name: __APP_ENV_NAME__
      labels:
        app: __APP_ENV_NAME__
    spec:
      containers:
      - name: yyt-server
        image: '__IMAGE__'
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
